## **NLP AI Applications**

## **A**) Download and install the Gutenberg corpus tool to your Jupyter Notebook. Project Gutenberg contains some 25,000 free electronic books, hosted at http://www.gutenberg.org/. We can install the NLTK package, then use the Gutenberg corpus in it.  Can be installed by running the following in computer terminal:

In [85]:
pip install nltk  #installing nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk) (1.15.0)

## **AB)** Download Gutenberg corpus tool in NLTK package

In [86]:
import nltk #imports the nltk
from nltk.corpus import gutenberg #importing gutenberg from the nltk corpus
nltk.download('gutenberg') #downloading gutenberg form nltk

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!

True

Here, we are donloading the gutenberg packages to nltk and ready to perform tasks.

## **AC)** Use the texts in the corpus.
## **AD)**Create a table displaying relative frequencies with which “modals” (can, could, may, might, will, would, and should) are used in all texts provided in the corpus.

In [87]:
cfd_1 = nltk.ConditionalFreqDist((genre, words)
for genre in gutenberg.fileids()
for words in gutenberg.words(fileids = genre))
genres = ['austen-emma.txt', 'austen-persuasion.txt', 'austen-sense.txt', 'bible-kjv.txt',
'blake-poems.txt', 'bryant-stories.txt', 'burgess-busterbrown.txt',
'carroll-alice.txt', 'chesterton-ball.txt', 'chesterton-brown.txt',
'chesterton-thursday.txt', 'edgeworth-parents.txt', 'melville-moby_dick.txt',
'milton-paradise.txt', 'shakespeare-caesar.txt', 'shakespeare-hamlet.txt',
'shakespeare-macbeth.txt', 'whitman-leaves.txt']
modals = ['can', 'could', 'may', 'might', 'would', 'will', 'shall']
cfd_1.tabulate(conditions=genres, samples=modals)

                          can could   may might would  will shall
        austen-emma.txt   270   825   213   322   815   559   212
  austen-persuasion.txt   100   444    87   166   351   162    55
       austen-sense.txt   206   568   169   215   507   354   123
          bible-kjv.txt   213   165  1024   475   443  3807  9760
        blake-poems.txt    20     3     5     2     3     3    15
     bryant-stories.txt    75   154    18    23   110   144    42
burgess-busterbrown.txt    23    56     3    17    46    19     0
      carroll-alice.txt    57    73    11    28    70    24    23
    chesterton-ball.txt   131   117    90    69   139   198    49
   chesterton-brown.txt   126   170    47    71   132   111    30
chesterton-thursday.txt   117   148    56    71   116   109    49
  edgeworth-parents.txt   340   420   160   127   503   517   263
 melville-moby_dick.txt   220   215   230   183   421   379    84
    milton-paradise.txt   107    62   116    98    49   161   241
 shakespeare-caesar.txt    16    18    35    12    40   129   107
 shakespeare-hamlet.txt    33    26    56    28    60   131   104
shakespeare-macbeth.txt    21    15    30     5    42    62    48
     whitman-leaves.txt    88    49    85    26    85   261   251

The table was created with all the text and displayed the number of repeated times with the genre names.

##**AE)** For two modals with the largest span of relative frequencies (most used minus least used), select a text which uses it the most and the text that uses it the least. Compare usage in both texts by examining the relative frequencies of those modals in two texts. Try to suggest an explanation for why those words are used differently in the two texts.

In [88]:
list_1=[ ]
list_2=[ ]
d={}
for text in nltk.corpus.gutenberg.fileids():
   list_2.append(text)
   fdist = nltk.FreqDist(w.lower() for w in gutenberg.words(text))
   print("\n",text)
   f= ([w.lower() for w in gutenberg.words(text) if w.isalpha()])
   t=len(f)

   for m in modals:
     d[m]=fdist[m]
   for m in modals:
     d[m]=d[m]/t
   print(d)

   value=d.values()
   max1=max(value)
   min1=min(value)
   fgap=max1-min1
   list_1.append(fgap)
   print("frequency diff:", fgap)

 austen-emma.txt
{'can': 0.0017574257425742575, 'could': 0.005179455445544555, 'may': 0.0013675742574257425, 'might': 0.0020173267326732674, 'would': 0.005074257425742574, 'will': 0.0035272277227722773, 'shall': 0.0013428217821782177}
frequency diff: 0.003836633663366337

 austen-persuasion.txt
{'can': 0.0012719772708360577, 'could': 0.005361324758383757, 'may': 0.0010342245099321215, 'might': 0.0019733479155026688, 'would': 0.004220111506044864, 'will': 0.0019852355535478657, 'shall': 0.0006775953685762176}
frequency diff: 0.004683729389807539

 austen-sense.txt
{'can': 0.0018056372325710452, 'could': 0.004787423488192955, 'may': 0.0014494794298162061, 'might': 0.001780789013774196, 'would': 0.0042656108934591205, 'will': 0.003006634474418759, 'shall': 0.001060190668665568}
frequency diff: 0.0037272328195273865

 bible-kjv.txt
{'can': 0.00029677637710553365, 'could': 0.00020963778127454719, 'may': 0.0012969759118612047, 'might': 0.0005998671452133128, 'would': 0.0005695580684025349, 'will': 0.004844400776922669, 'shall': 0.012424195736018044}
frequency diff: 0.012214557954743497

 blake-poems.txt
{'can': 0.004038073262186328, 'could': 0.0008653014133256418, 'may': 0.0008653014133256418, 'might': 0.00028843380444188056, 'would': 0.0007210845111047015, 'will': 0.0004326507066628209, 'shall': 0.0027401211421978658}
frequency diff: 0.0037496394577444473

 bryant-stories.txt
{'can': 0.0016734247280684818, 'could': 0.0033897577824976936, 'may': 0.0004719915899680333, 'might': 0.0004934457531483985, 'would': 0.002402866276200897, 'will': 0.003153761987513677, 'shall': 0.0009439831799360666}
frequency diff: 0.00291776619252966

 burgess-busterbrown.txt
{'can': 0.001469957738715012, 'could': 0.0034299013903350277, 'may': 0.0001837447173393765, 'might': 0.0010412200649231335, 'would': 0.002817418999203773, 'will': 0.00122496478226251, 'shall': 0.0}
frequency diff: 0.0034299013903350277

 carroll-alice.txt
{'can': 0.0023049061573921633, 'could': 0.0028171075257015328, 'may': 0.0004756155562872718, 'might': 0.0010244027366187393, 'would': 0.00303662239783412, 'will': 0.0012073317967292285, 'shall': 0.0009146453005524457}
frequency diff: 0.002561006841546848

 chesterton-ball.txt
{'can': 0.0017295179120001935, 'could': 0.00141506010981834, 'may': 0.0011610749619022278, 'might': 0.0008708062214266708, 'would': 0.0016932343194407489, 'will': 0.0024551897631890857, 'shall': 0.0006289156043637067}
frequency diff: 0.001826274158825379

 chesterton-brown.txt
{'can': 0.0017602270556450073, 'could': 0.002333324236552684, 'may': 0.0006549682067516306, 'might': 0.0009824523101274458, 'would': 0.001842098081488961, 'will': 0.0015964850039570995, 'shall': 0.00043664547116775373}
frequency diff: 0.0018966787653849303

 chesterton-thursday.txt
{'can': 0.0020775151556433487, 'could': 0.002571350725427423, 'may': 0.0010217287650704993, 'might': 0.001243103330835774, 'would': 0.0020434575301409986, 'will': 0.0020775151556433487, 'shall': 0.0009195558885634493}
frequency diff: 0.0016517948368639738

 edgeworth-parents.txt
{'can': 0.0021026491035920744, 'could': 0.0024950655101120436, 'may': 0.0011011087227724512, 'might': 0.0007438340840005388, 'would': 0.002992907219876184, 'will': 0.003256470477986611, 'shall': 0.0015989504325365914}
frequency diff: 0.002512636393986072

 melville-moby_dick.txt
{'can': 0.0010807790768498037, 'could': 0.0009891876296591424, 'may': 0.001099097366287936, 'might': 0.0008380617417945512, 'would': 0.001978375259318285, 'will': 0.001790612792577429, 'shall': 0.0004442185188747075}
frequency diff: 0.0015341567404435774

 milton-paradise.txt
{'can': 0.0016026238306436585, 'could': 0.0008323705166908924, 'may': 0.0015653535090007827, 'might': 0.0013293081385959027, 'would': 0.0007205595517622651, 'will': 0.0022734896202154225, 'shall': 0.0035158336749779484}
frequency diff: 0.0027952741232156833

 shakespeare-caesar.txt
{'can': 0.0009133737140659552, 'could': 0.0008653014133256418, 'may': 0.0018267474281319104, 'might': 0.0006249399096240747, 'would': 0.002115181232573791, 'will': 0.00783578502067109, 'shall': 0.006009037592539179}
frequency diff: 0.007210845111047015

 shakespeare-hamlet.txt
{'can': 0.0011564131368532347, 'could': 0.0010242516354985792, 'may': 0.00214762439701315, 'might': 0.0009912112601599154, 'would': 0.0024119473997224606, 'will': 0.004923015925460913, 'shall': 0.0035353201612370318}
frequency diff: 0.003931804665300997

 shakespeare-macbeth.txt
{'can': 0.0014229422066549913, 'could': 0.0008756567425569177, 'may': 0.0019154991243432575, 'might': 0.00043782837127845885, 'would': 0.0029006129597197896, 'will': 0.00394045534150613, 'shall': 0.0037215411558669}
frequency diff: 0.0035026269702276708

 whitman-leaves.txt
{'can': 0.0007285628306249802, 'could': 0.00041179638252716275, 'may': 0.0007839969590420983, 'might': 0.00020589819126358137, 'would': 0.0007364819918274256, 'will': 0.0021619310082676042, 'shall': 0.00208273939624315}
frequency diff: 0.001956032817004023

In [89]:
print(max(list_1))

0.012214557954743497

firstly, two empty array lists were created and two for loops inside the for loops to check the difference between each word we have considered earlier. Finally, we got the frequency difference for each individual file.  This file which has max frequency gap is ("*Max modal bible-kjv.txt *"  with 0.012214557954743497 ) and Min frequency gap is ("* Min modal Melville-moby_dick.txt *" with 0.0015341567404435774 ).

In [90]:
max_index=list_1.index((max(list_1)))
min_index=list_1.index((min(list_1)))
print(" Max modal " + list_2[max_index])
print(" Min modal " + list_2[min_index])
mst_used_text=[list_2[max_index], list_2[min_index]]

from nltk.text import Text
for text1 in nltk.corpus.gutenberg.fileids(): #loop to execute the text in most used texts
  if(text1 in mst_used_text): 
   moby= Text(nltk.corpus.gutenberg.words(text1))
   for m in modals:
    result = moby.concordance(m) #We can use a concordance to see terms in context.
    print(result)

 Max modal bible-kjv.txt
 Min modal melville-moby_dick.txt
Displaying 25 of 236 matches:
les , the motion of whose vast bodies can in a peaceful calm trouble the ocean
 the - Whale . ... Some say the whale can ' t open his mouth , but that is a fa
limb up the masts to see whether they can see a whale , for the first discovere
" Myself have agreed to try whether I can master and kill this Sperma - ceti wh
 high time to get to sea as soon as I can . This is my substitute for pistol an
st as nigh the water as they possibly can without falling in . And there they s
whatsoever . It is quite as much as I can do to take care of myself , without t
earthly ills , and that on no account can a monied man enter heaven . Ah ! how
es me in some unaccountable way -- he can better answer than any one else . And
all all the circumstances , I think I can see a little into the springs and mot
own coals . But what thinks Lazarus ? Can he warm his blue hands by holding the
ps him so late , unless , may be , he can ' t sell his head ." " Can ' t sell h
ay be , he can ' t sell his head ." " Can ' t sell his head ?-- What sort of a
ain , and that ' s the very reason he can ' t sell it , I guess ." " Landlord ,
ouse and want a bed ; you tell me you can only give me half a one ; that the ot
sfactory conclusion concerning it . I can compare it to nothing but a large doo
all ! It ' s only his outside ; a man can be honest in any sort of skin . But t
p hither from the bottom of the sea . Can Herr Alexander perform a feat like th
en grass ; who standing among flowers can say -- here , HERE lies my beloved ;
 it must symbolize something unseen . Can it be , then , that by that act of ph
there ; Which none but they that feel can tell -- Oh , I was plunging to despai
ons of the man assure the mariners he can be no innocent . In their gamesome bu
d , shipmates , sin that pays its way can travel freely , and without a passpor
ows of the seas of the boisterous mob can never shake from this sure Keel of th
be his , who coming to lay him down , can say with his final breath -- O Father
None
Displaying 25 of 216 matches:
atever random allusions to whales he could anyways find in any book whatsoever
for ever go thankless ! Would that I could clear out Hampton Court and the Tuil
ill this Sperma - ceti whale , for I could never hear of any of that sort that
 story of Narcissus , who because he could not grasp the tormenting , mild imag
 am quick to perceive a horror , and could still be social with it -- would the
ing before me in New Bedford , ere I could embark for my destined port , it bec
 inquiry of the neighbors , that you could any way arrive at an understanding o
d what monstrous cannibal and savage could ever have gone a death - harvesting
ere afore long ," was the answer . I could not help it , but I began to feel su
tumble in upon me at midnight -- how could I tell from what vile hole he had be
now how all the planing in the world could make eider down of a pine plank . So
t it was a foot too short ; but that could be mended with a chair . But it was
nd thoughts I dismissed it . For who could tell but what the next morning , so
ling me -- but at the same time what could I think of a harpooneer who stayed o
ides the bedstead and centre table , could see no other furniture belonging to
same in South American ponchos . But could it be possible that any sober harpoo
but I rolled about a good deal , and could not sleep for a long time . At last
 the light , that I plainly saw they could not be sticking - plasters at all ,
ng into bed with me . I sang out , I could not help it now ; and giving a sudde
s the arm did when I first awoke , I could hardly tell it from the quilt , they
 sense of weight and pressure that I could tell that Queequeg was hugging me .
t was a reality or a dream , I never could entirely settle . The circumstance w
en entire hours must elapse before I could hope for a resurrection . Sixteen ho
y hand ; yet ever thinking that if I could but stir it one single inch , the ho
boots on ; I begged him as well as I could , to accelerate his toilet somewhat
None
Displaying 25 of 240 matches:
ng more in those southern seas , as I may say , by a hundred to one ; than we h
ut did not take any till the first of May , the sea being then covered with the
 the vicinity of London and elsewhere may recollect having seen large curved bo
 , or entrances to alcoves , and they may perhaps have been told that these wer
par to spar , like a grasshopper in a May meadow . And at first , this sort of
then , however the old sea - captains may order me about -- however they may th
ns may order me about -- however they may thump and punch me about , I have the
thence to embark on their voyage , it may as well be related that I , for one ,
 south -- wherever in your wisdom you may conclude to lodge for the night , my
what sort of a place this " Spouter " may be . CHAPTER 3 The Spouter - Inn . En
right whale ' s head . Be that how it may , there stands the vast arched bone o
 -- the Cape Horn measure , which you may gulp down for a shilling . Upon enter
ood look at him then , and perhaps we may become jolly good bedfellows after al
on airth keeps him so late , unless , may be , he can ' t sell his head ." " Ca
at yarn to me -- I ' m not green ." " May be not ," taking out a stick and whit
od night , landlord ," said I , " you may go ." I turned in , and never slept b
nces -- this kind of travel , I say , may not be the very best mode of attainin
re me . Yes , Ishmael , the same fate may be thine . But somehow I grew merry a
 . I have read ye by what murky light may be mine the lesson that Jonah teaches
phrenologically an excellent one . It may seem ridiculous , but it reminded me
to present the whole story such as it may prove in the mere skeleton I give . C
t this was the very ship for us . You may have seen many a quaint craft in your
ard the labors of this young man , we may be taking the bread from those widows
id Bildad steadily , " thy conscience may be drawing ten inches of water , or t
; but , when he does speak , then you may well listen . Mark ye , be forewarned
None
Displaying 25 of 183 matches:
DIBERT . " What spermacetti is , men might justly doubt , since the learned Hos
In his ocean home will be A giant in might , where might is right , And King of
ome will be A giant in might , where might is right , And King of the boundless
 wooden house itself looked as if it might have been carted here from the ruins
his tatters with his shiverings , he might plug up both ears with rags , and pu
n that such an idea , however wild , might not be altogether unwarranted . But
he whale ' s jaw , so wide , a coach might almost drive beneath it . Within are
would depend upon who the harpooneer might be , and that if he ( the landlord )
, his linen or woollen , as the case might be , would not be of the tidiest , c
ped out of the room , the harpooneer might be standing in the entry , all ready
 , I began to think that after all I might be cherishing unwarrantable prejudic
uares of tattooing . To be sure , it might be nothing but a good coat of tropic
s the heads of his own brothers . He might take a fancy to mine -- heavens ! lo
onjured him , whoever or whatever he might be , to keep quiet , and let me get
him looks a few shades lighter ; you might say a touch of satin wood is in him
y perished without a grave . As well might those tablets stand in the cave of E
n at last relented , and told him he might make himself at home . But this fine
 no seeming ignominy , if thereby he might happily gain the power of enlighteni
, and having a coronation ; since he might now consider his father dead and gon
 of a sceptre now . I asked him what might be his immediate purpose , touching
. " Why ," said I , " Queequeg , you might have known better than that , one wo
 mean by that ? Don ' t you know you might have killed that chap ?" " What him
t particular whale , though indeed I might have inferred as much from the simpl
oceeds of the voyage , whatever that might eventually amount to . And though th
ing ; and if we had a lucky voyage , might pretty nearly pay for the clothing I
None
Displaying 25 of 432 matches:
warm ; and for whom even Pale Sherry would be too rosy - strong ; but with whom
ore shall ye for ever go thankless ! Would that I could clear out Hampton Court
keth a path to shine after him ; One would think the deep to be hoary ." -- JOB
rite a fable for little fishes , you would make them speak like great wales ."
of as pretty rainbows as a Christian would wish to look at . He ' s a raal oil
 be sure ; but bethink you , how you would manage a powerful unbroken colt , wi
o interest me on shore , I thought I would sail about a little and see the wate
ere Niagara but a cataract of sand , would you travel your thousand miles to se
th other men , perhaps , such things would not have been inducements ; but as f
and could still be social with it -- would they let me -- since it is but well
d that no way of reaching that place would offer , till the following Monday .
 - cob into his mouth , and yet that would not keep out the tempestuous Eurocly
em up to the grand northern lights ? Would not Lazarus rather be in Sumatra tha
rus rather be in Sumatra than here ? Would he not far rather lay him down lengt
bright , but , alas , deceptive idea would dart you through .-- It ' s the Blac
d wrinkled planks beneath , that you would almost fancy you trod some old craft
d ; that if I should ever do so , it would depend upon who the harpooneer might
trange town on so bitter a night , I would put up with the half of any decent m
o sleep two in a bed . In fact , you would a good deal rather not sleep with yo
 or woollen , as the case might be , would not be of the tidiest , certainly no
 sill of the window , that this plan would never do at all , especially as anot
ng to induce me to do so knowingly , would thereby render yourself liable to a
ause to - morrow ' s Sunday , and it would not do to be sellin ' human heads ab
e possible that any sober harpooneer would get into a door mat , and parade the
er stood between me and the door , I would have bolted out of it quicker than e
None
Displaying 25 of 391 matches:
ied by a Sub - Sub - Librarian ). It will be seen that this mere painstaking b
ow tribe which no wine of this world will ever warm ; and for whom even Pale S
h that an incredible quantity of oil will be extracted out of one whale ." --
 with a boat as near the shore as it will come ; but it will be aground in twe
r the shore as it will come ; but it will be aground in twelve or thirteen fee
ode in the deep , we shall find they will appear contemptible in the compariso
re our children ' s grand - children will go for bread ." -- OBED MACY ' S HIS
bit of noise ," replied Samuel , " I will send you to hell ." -- LIFE OF SAMUE
mid storm and gale In his ocean home will be A giant in might , where might is
bound for a dive . Strange ! Nothing will content them but the extremest limit
r the shady lee of yonder warehouses will not suffice . No . They must get jus
gs , set his feet a - going , and he will infallibly lead you to water , if wa
d and peppered , there is no one who will speak more respectfully , not to say
rentially , of a broiled fowl than I will . It is out of the idolatrous doting
ed upon us . But BEING PAID ,-- what will compare with it ? The urbane activit
 as this narrative is concerned ), I will here venture upon a little descripti
h him . And in the first place , you will be so good as to unsay that story ab
m to stop smoking , in short , and I will turn in with him . But I don ' t fan
ate sense of delicacy , say what you will ; it is marvellous how essentially p
ng coolly is to do it genteelly . We will not speak of all Queequeg ' s peculi
the docks , any considerable seaport will frequently offer to view the queeres
nut streets , Mediterranean mariners will sometimes jostle the affrighted ladi
nheeded reel about the streets , you will see other sights still more curious
mbazine cloak . No town - bred dandy will compare with a country - bred one --
 a fellow that , in the dog - days , will mow his two acres in buckskin gloves
None
Displaying 25 of 97 matches:
ease the world , by so much the more shall ye for ever go thankless ! Would tha
ntered hearts together -- there , ye shall strike unsplinterable glasses ! EXTR
ore , and great , and strong sword , shall punish Leviathan the piercing serpen
iathan that crooked serpent ; and he shall slay the dragon that is in the sea .
take up their abode in the deep , we shall find they will appear contemptible i
t this harpooneer is , and whether I shall be in all respects safe to spend the
y Deliverer God . " My song for ever shall record That terrible , that joyful h
 that stifling hour , when the whale shall hold him in the smallest of his bowe
othing , Sir ; but I have no doubt I shall soon learn . I ' ve been several voy
Peleg , " what d ' ye say , what lay shall we give this young man ?" " Thou kno
ou are determined that I , for one , shall not LAY up many LAYS here below , wh
end with me who wants to ship too -- shall I bring him down to - morrow ?" " To
d uncleanliness of our business , ye shall soon be initiated into certain facts
ndiscovered prime thing in me ; if I shall ever deserve any real repute in that
onably ambitious of ; if hereafter I shall do anything that , upon the whole ,
d anywhere in this fishery ." But we shall ere long see what that word " carefu
rs , and renegades and castaways , I shall hereafter ascribe high qualities , t
e the most abased , among them all , shall at times lift himself to the exalted
himself to the exalted mounts ; if I shall touch that workman ' s arm with some
 arm with some ethereal light ; if I shall spread a rainbow over his disastrous
 the grim Pequod ' s forecastle , ye shall ere long see him , beating his tambo
launched upon the deep ; but soon we shall be lost in its unshored , harbourles
very reason infallibly be faulty . I shall not pretend to a minute anatomical d
ngless and cold blooded . Next : how shall we define the whale , by his obvious
divisible into CHAPTERS ), and these shall comprehend them all , both small and
None
Displaying 25 of 236 matches:
les , the motion of whose vast bodies can in a peaceful calm trouble the ocean
 the - Whale . ... Some say the whale can ' t open his mouth , but that is a fa
limb up the masts to see whether they can see a whale , for the first discovere
" Myself have agreed to try whether I can master and kill this Sperma - ceti wh
 high time to get to sea as soon as I can . This is my substitute for pistol an
st as nigh the water as they possibly can without falling in . And there they s
whatsoever . It is quite as much as I can do to take care of myself , without t
earthly ills , and that on no account can a monied man enter heaven . Ah ! how
es me in some unaccountable way -- he can better answer than any one else . And
all all the circumstances , I think I can see a little into the springs and mot
own coals . But what thinks Lazarus ? Can he warm his blue hands by holding the
ps him so late , unless , may be , he can ' t sell his head ." " Can ' t sell h
ay be , he can ' t sell his head ." " Can ' t sell his head ?-- What sort of a
ain , and that ' s the very reason he can ' t sell it , I guess ." " Landlord ,
ouse and want a bed ; you tell me you can only give me half a one ; that the ot
sfactory conclusion concerning it . I can compare it to nothing but a large doo
all ! It ' s only his outside ; a man can be honest in any sort of skin . But t
p hither from the bottom of the sea . Can Herr Alexander perform a feat like th
en grass ; who standing among flowers can say -- here , HERE lies my beloved ;
 it must symbolize something unseen . Can it be , then , that by that act of ph
there ; Which none but they that feel can tell -- Oh , I was plunging to despai
ons of the man assure the mariners he can be no innocent . In their gamesome bu
d , shipmates , sin that pays its way can travel freely , and without a passpor
ows of the seas of the boisterous mob can never shake from this sure Keel of th
be his , who coming to lay him down , can say with his final breath -- O Father
None
Displaying 25 of 216 matches:
atever random allusions to whales he could anyways find in any book whatsoever
for ever go thankless ! Would that I could clear out Hampton Court and the Tuil
ill this Sperma - ceti whale , for I could never hear of any of that sort that
 story of Narcissus , who because he could not grasp the tormenting , mild imag
 am quick to perceive a horror , and could still be social with it -- would the
ing before me in New Bedford , ere I could embark for my destined port , it bec
 inquiry of the neighbors , that you could any way arrive at an understanding o
d what monstrous cannibal and savage could ever have gone a death - harvesting
ere afore long ," was the answer . I could not help it , but I began to feel su
tumble in upon me at midnight -- how could I tell from what vile hole he had be
now how all the planing in the world could make eider down of a pine plank . So
t it was a foot too short ; but that could be mended with a chair . But it was
nd thoughts I dismissed it . For who could tell but what the next morning , so
ling me -- but at the same time what could I think of a harpooneer who stayed o
ides the bedstead and centre table , could see no other furniture belonging to
same in South American ponchos . But could it be possible that any sober harpoo
but I rolled about a good deal , and could not sleep for a long time . At last
 the light , that I plainly saw they could not be sticking - plasters at all ,
ng into bed with me . I sang out , I could not help it now ; and giving a sudde
s the arm did when I first awoke , I could hardly tell it from the quilt , they
 sense of weight and pressure that I could tell that Queequeg was hugging me .
t was a reality or a dream , I never could entirely settle . The circumstance w
en entire hours must elapse before I could hope for a resurrection . Sixteen ho
y hand ; yet ever thinking that if I could but stir it one single inch , the ho
boots on ; I begged him as well as I could , to accelerate his toilet somewhat
None
Displaying 25 of 240 matches:
ng more in those southern seas , as I may say , by a hundred to one ; than we h
ut did not take any till the first of May , the sea being then covered with the
 the vicinity of London and elsewhere may recollect having seen large curved bo
 , or entrances to alcoves , and they may perhaps have been told that these wer
par to spar , like a grasshopper in a May meadow . And at first , this sort of
then , however the old sea - captains may order me about -- however they may th
ns may order me about -- however they may thump and punch me about , I have the
thence to embark on their voyage , it may as well be related that I , for one ,
 south -- wherever in your wisdom you may conclude to lodge for the night , my
what sort of a place this " Spouter " may be . CHAPTER 3 The Spouter - Inn . En
right whale ' s head . Be that how it may , there stands the vast arched bone o
 -- the Cape Horn measure , which you may gulp down for a shilling . Upon enter
ood look at him then , and perhaps we may become jolly good bedfellows after al
on airth keeps him so late , unless , may be , he can ' t sell his head ." " Ca
at yarn to me -- I ' m not green ." " May be not ," taking out a stick and whit
od night , landlord ," said I , " you may go ." I turned in , and never slept b
nces -- this kind of travel , I say , may not be the very best mode of attainin
re me . Yes , Ishmael , the same fate may be thine . But somehow I grew merry a
 . I have read ye by what murky light may be mine the lesson that Jonah teaches
phrenologically an excellent one . It may seem ridiculous , but it reminded me

 Max modal bible-kjv.txt
 Min modal melville-moby_dick.txt
 
These two texts were compared with examining the relative frequencies of the two text which are Max and Min modals. Out of minimum or maximum of all the verbs from two texts displyaing only 25.

## **B)** In the Inaugural corpus, see below:

In [91]:
from nltk.corpus import inaugural
nltk.download('inaugural')  #dowloading inaugural
from collections import Counter
from nltk import FreqDist #importing frequence distance
import pandas as pd
from nltk.corpus import wordnet as wn #importing wordnet as wn and downloading 
nltk.download('wordnet')
import numpy as np

[nltk_data] Downloading package inaugural to /root/nltk_data...
[nltk_data]   Package inaugural is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

## **BA)** Choose Kennedy’s speech, using e.g. this code:

In [92]:
np_words = nltk.corpus.inaugural.words('1961-Kennedy.txt')

##**BB)** Identify the 10 most frequently used long words (words longer than 7 characters).

In [93]:
# Filter's the character
flt_char = ([w.lower() for w in np_words if len(w) > 7])

# Frequency distribution
f_dst = FreqDist(flt_char)
freq = f_dst.most_common(10)

# Creating empty arrays
e_1 = []
e_2 = []

# To Seperate the words
for i in range(10):
    e_1.append(freq[i][0])

for i in range(10):
    e_2.append(freq[i][1])

# To Create dataframe 
df_freq = pd.DataFrame({'Most Frequently Used Top_10':e_1, 'Repeated No.Of Times':e_2})

In [94]:
df_freq

  Most Frequently Used Top_10  Repeated No.Of Times
0                    citizens                     5
1                   president                     4
2                   americans                     4
3                  generation                     3
4                   forebears                     2
5                  revolution                     2
6                   committed                     2
7                    powerful                     2
8                  supporting                     2
9                  themselves                     2

Here are the top 10 words used most frequently which has each word more than seven character's.

##**BC)** Which one of those 10 words has the largest number of synonyms? Use WordNet as a helper:

In [95]:
# Creating an array
np_syn = []

# Loop trough the distribution
for i in f_dst.most_common(10):
    
    print ('Word: ', i[0])
    count=0
    
    # Print synonym
    print ('Synonymns: ')
    for j in wn.synsets(i[0]):
        print ('  ',j.lemma_names())
        count+=len(j.lemma_names())
    np_syn.append([i[0], count])

Word:  citizens
Synonymns:
   ['citizen']
Word:  president
Synonymns:
   ['president']
   ['President_of_the_United_States', 'United_States_President', 'President', 'Chief_Executive']
   ['president']
   ['president', 'chairman', 'chairwoman', 'chair', 'chairperson']
   ['president', 'prexy']
   ['President_of_the_United_States', 'President', 'Chief_Executive']
Word:  americans
Synonymns:
   ['American']
   ['American_English', 'American_language', 'American']
   ['American']
Word:  generation
Synonymns:
   ['coevals', 'contemporaries', 'generation']
   ['generation']
   ['generation']
   ['generation']
   ['genesis', 'generation']
   ['generation']
   ['generation', 'multiplication', 'propagation']
Word:  forebears
Synonymns:
   ['forebear', 'forbear']
Word:  revolution
Synonymns:
   ['revolution']
   ['revolution']
   ['rotation', 'revolution', 'gyration']
Word:  committed
Synonymns:
   ['perpetrate', 'commit', 'pull']
   ['give', 'dedicate', 'consecrate', 'commit', 'devote']
   ['commit', 'institutionalize', 'institutionalise', 'send', 'charge']
   ['entrust', 'intrust', 'trust', 'confide', 'commit']
   ['invest', 'put', 'commit', 'place']
   ['commit', 'practice']
   ['committed']
   ['attached', 'committed']
Word:  powerful
Synonymns:
   ['powerful']
   ['knock-down', 'powerful']
   ['potent', 'powerful']
   ['brawny', 'hefty', 'muscular', 'powerful', 'sinewy']
   ['herculean', 'powerful']
   ['mighty', 'mightily', 'powerful', 'right']
Word:  supporting
Synonymns:
   ['support', 'supporting']
   ['support', 'back_up']
   ['support']
   ['back', 'endorse', 'indorse', 'plump_for', 'plunk_for', 'support']
   ['hold', 'support', 'sustain', 'hold_up']
   ['confirm', 'corroborate', 'sustain', 'substantiate', 'support', 'affirm']
   ['subscribe', 'support']
   ['corroborate', 'underpin', 'bear_out', 'support']
   ['defend', 'support', 'fend_for']
   ['support']
   ['patronize', 'patronise', 'patronage', 'support', 'keep_going']
   ['digest', 'endure', 'stick_out', 'stomach', 'bear', 'stand', 'tolerate', 'support', 'brook', 'abide', 'suffer', 'put_up']
   ['encouraging', 'supporting']
   ['load-bearing', 'supporting']
Word:  themselves
Synonymns:

Using wordnet as a helper to print the synonyms for the top 10 words which have more than seven characters. Started with creating an empty array and used for loop to find the most common 10 words and created another for loop inside the for loop to print the synonym for each top word.

In [96]:
# Creaty empty arrays
e_1 = []
e_2 = []

# Get synonyms
for i in range(10):
    e_1.append(np_syn[i][0])

for j in range(10):
    e_2.append(np_syn[j][1])

# Create dataframe
df_sn = pd.DataFrame({'Most Frequently Used Top_10':e_1, 'No.Of synonyms':e_2})

In [97]:
df_sn.sort_values(by="No.Of synonyms", ascending=False)

  Most Frequently Used Top_10  No.Of synonyms
8                  supporting              52
6                   committed              27
1                   president              16
7                    powerful              16
3                  generation              12
2                   americans               5
5                  revolution               5
4                   forebears               2
0                    citizens               1
9                  themselves               0

Listing all the most used words with the total number of synonyms and sorting in asceding order.

##**BD)** List all synonyms for the 10 most frequently used words. Which one of those 10 words has the largest number of hyponyms?

In [98]:
# Create array
a_hyp = []

# Loop trough distribution
for i in f_dst.most_common(10):
    # Print word
    print ('Word: ', i[0])
    count=0
    
    # Print Hyponyms
    print ('Hyponyms: ')
    for j in wn.synsets(i[0]):
        print (j)
        print (j.hyponyms())
        count+= len(j.hyponyms())
    a_hyp.append([i[0], count])

Word:  citizens
Hyponyms:
Synset('citizen.n.01')
[Synset('active_citizen.n.01'), Synset('civilian.n.01'), Synset('freeman.n.01'), Synset('private_citizen.n.01'), Synset('repatriate.n.01'), Synset('thane.n.02'), Synset('voter.n.01')]
Word:  president
Hyponyms:
Synset('president.n.01')
[]
Synset('president_of_the_united_states.n.01')
[]
Synset('president.n.03')
[Synset('ex-president.n.01')]
Synset('president.n.04')
[Synset('kalon_tripa.n.01'), Synset('vice_chairman.n.01')]
Synset('president.n.05')
[]
Synset('president_of_the_united_states.n.02')
[]
Word:  americans
Hyponyms:
Synset('american.n.01')
[Synset('african-american.n.01'), Synset('alabaman.n.01'), Synset('alaskan.n.01'), Synset('anglo-american.n.01'), Synset('appalachian.n.01'), Synset('arizonan.n.01'), Synset('arkansan.n.01'), Synset('asian_american.n.01'), Synset('bay_stater.n.01'), Synset('bostonian.n.01'), Synset('californian.n.01'), Synset('carolinian.n.01'), Synset('coloradan.n.01'), Synset('connecticuter.n.01'), Synset('creole.n.02'), Synset('delawarean.n.01'), Synset('floridian.n.01'), Synset('franco-american.n.01'), Synset('georgian.n.01'), Synset('german_american.n.01'), Synset('hawaiian.n.02'), Synset('idahoan.n.01'), Synset('illinoisan.n.01'), Synset('indianan.n.01'), Synset('iowan.n.01'), Synset('kansan.n.01'), Synset('kentuckian.n.01'), Synset('louisianan.n.01'), Synset('mainer.n.01'), Synset('marylander.n.01'), Synset('michigander.n.01'), Synset('minnesotan.n.01'), Synset('mississippian.n.02'), Synset('missourian.n.01'), Synset('montanan.n.01'), Synset('nebraskan.n.01'), Synset('nevadan.n.01'), Synset('new_englander.n.01'), Synset('new_hampshirite.n.01'), Synset('new_jerseyan.n.01'), Synset('new_mexican.n.01'), Synset('new_yorker.n.01'), Synset('nisei.n.01'), Synset('north_carolinian.n.01'), Synset('north_dakotan.n.01'), Synset('ohioan.n.01'), Synset('oklahoman.n.01'), Synset('oregonian.n.01'), Synset('pennsylvanian.n.02'), Synset('puerto_rican.n.01'), Synset('rhode_islander.n.01'), Synset('south_carolinian.n.01'), Synset('south_dakotan.n.01'), Synset('southerner.n.01'), Synset('spanish_american.n.01'), Synset('tennessean.n.01'), Synset('texan.n.01'), Synset('tory.n.01'), Synset('utahan.n.01'), Synset('vermonter.n.01'), Synset('virginian.n.01'), Synset('washingtonian.n.01'), Synset('washingtonian.n.02'), Synset('west_virginian.n.01'), Synset('wisconsinite.n.01'), Synset('wyomingite.n.01'), Synset('yankee.n.01'), Synset('yankee.n.03')]
Synset('american_english.n.01')
[Synset('african_american_vernacular_english.n.01')]
Synset('american.n.03')
[Synset('creole.n.01'), Synset('latin_american.n.01'), Synset('mesoamerican.n.01'), Synset('north_american.n.01'), Synset('south_american.n.01'), Synset('west_indian.n.01')]
Word:  generation
Hyponyms:
Synset('coevals.n.01')
[Synset('peer_group.n.01'), Synset('youth_culture.n.01')]
Synset('generation.n.02')
[Synset('baby_boom.n.01'), Synset('generation_x.n.01'), Synset('posterity.n.02')]
Synset('generation.n.03')
[]
Synset('generation.n.04')
[]
Synset('genesis.n.01')
[]
Synset('generation.n.06')
[]
Synset('generation.n.07')
[Synset('biogenesis.n.02')]
Word:  forebears
Hyponyms:
Synset('forebear.n.01')
[Synset('grandparent.n.01'), Synset('great_grandparent.n.01')]
Word:  revolution
Hyponyms:
Synset('revolution.n.01')
[Synset('cultural_revolution.n.01'), Synset('green_revolution.n.01')]
Synset('revolution.n.02')
[Synset('counterrevolution.n.01')]
Synset('rotation.n.03')
[Synset('axial_rotation.n.01'), Synset('dextrorotation.n.01'), Synset('levorotation.n.01'), Synset('orbital_rotation.n.01'), Synset('spin.n.01')]
Word:  committed
Hyponyms:
Synset('perpetrate.v.01')
[Synset('make.v.24'), Synset('recommit.v.01')]
Synset('give.v.18')
[Synset('apply.v.10'), Synset('rededicate.v.01'), Synset('vow.v.02')]
Synset('commit.v.03')
[Synset('hospitalize.v.01')]
Synset('entrust.v.01')
[Synset('commend.v.03'), Synset('consign.v.02'), Synset('obligate.v.02'), Synset('recommit.v.02')]
Synset('invest.v.01')
[Synset('buy_into.v.01'), Synset('fund.v.04'), Synset('roll_over.v.03'), Synset('shelter.v.02'), Synset('speculate.v.04'), Synset('tie_up.v.02')]
Synset('commit.v.06')
[]
Synset('committed.a.01')
[]
Synset('attached.a.03')
[]
Word:  powerful
Hyponyms:
Synset('powerful.a.01')
[]
Synset('knock-down.s.01')
[]
Synset('potent.s.01')
[]
Synset('brawny.s.01')
[]
Synset('herculean.s.01')
[]
Synset('mighty.r.01')
[]
Word:  supporting
Hyponyms:
Synset('support.n.08')
[Synset('shoring.n.02'), Synset('suspension.n.06')]
Synset('support.v.01')
[Synset('help.v.01'), Synset('patronize.v.02'), Synset('promote.v.01'), Synset('second.v.01'), Synset('sponsor.v.02'), Synset('undergird.v.01')]
Synset('support.v.02')
[Synset('fund.v.06'), Synset('provide.v.06'), Synset('see_through.v.01'), Synset('sponsor.v.01'), Synset('subsidize.v.01')]
Synset('back.v.01')
[Synset('champion.v.01'), Synset('guarantee.v.04')]
Synset('hold.v.10')
[Synset('block.v.11'), Synset('brace.v.03'), Synset('bracket.v.01'), Synset('buoy.v.02'), Synset('carry.v.05'), Synset('chock.v.02'), Synset('pole.v.02'), Synset('prop_up.v.01'), Synset('scaffold.v.01'), Synset('truss.v.03'), Synset('underpin.v.01')]
Synset('confirm.v.01')
[Synset('back.v.09'), Synset('document.v.02'), Synset('prove.v.02'), Synset('validate.v.02'), Synset('verify.v.01'), Synset('vouch.v.04')]
Synset('subscribe.v.03')
[]
Synset('corroborate.v.03')
[]
Synset('defend.v.01')
[Synset('apologize.v.02'), Synset('stand_up.v.05'), Synset('uphold.v.02')]
Synset('support.v.09')
[]
Synset('patronize.v.04')
[]
Synset('digest.v.03')
[Synset('accept.v.07'), Synset('bear_up.v.01'), Synset('pay.v.09'), Synset('sit_out.v.02'), Synset('stand_for.v.04'), Synset('take_a_joke.v.01'), Synset('take_lying_down.v.01')]
Synset('encouraging.s.02')
[]
Synset('load-bearing.s.01')
[]
Word:  themselves
Hyponyms:

##**BE)** List all hyponyms of the 10 most frequently used words.

In [99]:
# Creating Empty Arrays
e_1 = []
e_2 = []

# Get Hyponyms
for i in range(10):
    e_1.append(a_hyp[i][0])

for j in range(10):
    e_2.append(a_hyp[j][1])

# Create dataframe
df_hy = pd.DataFrame({'Most Frequently Used Top_10':e_1, 'No.Of Hyponyms':e_2})

In [100]:
df_hy.sort_values(by="No.Of Hyponyms", ascending=False)

  Most Frequently Used Top_10  No.Of Hyponyms
2                   americans              75
8                  supporting              42
6                   committed              16
5                  revolution               8
0                    citizens               7
3                  generation               6
1                   president               3
4                   forebears               2
7                    powerful               0
9                  themselves               0

Listing all the hyponyms of most frequently used words. Americans words has max number of hyponyms and powerful and themselves has the min number of hyoinyms which is zero.